'use client'

import { useState, useEffect, useCallback } from 'react'
import { Project, Layer } from './workspace-client'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { LayerDescriptions } from './layer-descriptions'
import { LayerActions } from './layer-actions'
import { Sparkles, PenLine, ArrowRight, Zap } from 'lucide-react'
import { callGenerateWebhook } from '@/lib/webhooks'
import { updateLayerStatus } from '@/app/actions'
import { useRouter } from 'next/navigation'

// Layers 4–8 are auto-generated (0-indexed: indices 3–7)
const AUTO_GENERATED_LAYER_KEYS = new Set([
  'need_extraction',
  'system_design',
  'architecture',
  'implementation_plan',
  'verification_plan',
])

export function isAutoGeneratedLayer(layerKey: string): boolean {
  return AUTO_GENERATED_LAYER_KEYS.has(layerKey)
}

// ─── Input extraction ────────────────────────────────────────────────────────
function extractUserInput(raw: unknown): string {
  if (!raw) return ''
  if (typeof raw === 'string') {
    try {
      const parsed = JSON.parse(raw)
      if (parsed && typeof parsed === 'object') {
        if (typeof parsed.response === 'string') return parsed.response
        if (typeof parsed.builderInput === 'string') return parsed.builderInput
      }
    } catch { /* plain text */ }
    return raw
  }
  if (typeof raw === 'object') {
    const obj = raw as Record<string, unknown>
    if (typeof obj.builderInput === 'string') return obj.builderInput
    if (typeof obj.response === 'string') return obj.response
    return JSON.stringify(obj, null, 2)
  }
  return ''
}

// ─── AI Output rendering ─────────────────────────────────────────────────────
function formatKey(key: string): string {
  return key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
}

function FieldValue({ value }: { value: unknown }) {
  if (Array.isArray(value)) {
    return (
      <ul className="space-y-1.5 mt-1">
        {value.map((item, i) => {
          if (item && typeof item === 'object' && !Array.isArray(item)) {
            return <ObjectCard key={i} obj={item as Record<string, unknown>} />
          }
          return (
            <li key={i} className="flex gap-2.5 text-sm text-foreground leading-relaxed">
              <span className="mt-2 h-1.5 w-1.5 rounded-full bg-primary/60 flex-shrink-0" />
              <span>{String(item)}</span>
            </li>
          )
        })}
      </ul>
    )
  }
  if (value && typeof value === 'object') {
    return <ObjectCard obj={value as Record<string, unknown>} />
  }
  if (typeof value === 'boolean') {
    return (
      <span className={`inline-flex items-center gap-1 text-sm font-medium ${value ? 'text-emerald-500' : 'text-muted-foreground'}`}>
        {value ? '✓ Yes' : '✗ No'}
      </span>
    )
  }
  return <p className="text-sm text-foreground leading-relaxed mt-1">{String(value)}</p>
}

function ObjectCard({ obj }: { obj: Record<string, unknown> }) {
  return (
    <div className="rounded-lg border border-border bg-muted/30 p-3 space-y-2 mt-1">
      {Object.entries(obj).map(([k, v]) => (
        <div key={k}>
          <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
            {formatKey(k)}
          </span>
          {Array.isArray(v) ? (
            <ul className="mt-1 space-y-1">
              {v.map((item, i) => (
                <li key={i} className="flex gap-2 text-xs text-foreground">
                  <ArrowRight className="h-3 w-3 mt-0.5 flex-shrink-0 text-muted-foreground" />
                  <span>{typeof item === 'object' ? JSON.stringify(item) : String(item)}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-foreground mt-0.5 leading-relaxed">{String(v ?? '')}</p>
          )}
        </div>
      ))}
    </div>
  )
}

function AiOutputDisplay({ value, isLoading }: { value: unknown; isLoading?: boolean }) {
  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-48 gap-3 text-center">
        <Sparkles className="h-8 w-8 text-primary/40 animate-pulse" />
        <p className="text-sm text-muted-foreground">Auto-generating with AI…</p>
      </div>
    )
  }

  if (value === null || value === undefined) {
    return (
      <div className="flex flex-col items-center justify-center h-48 gap-3 text-center">
        <Sparkles className="h-8 w-8 text-muted-foreground/30" />
        <p className="text-sm text-muted-foreground leading-relaxed max-w-xs">
          Enter your response and click <span className="font-semibold text-foreground">Generate</span> to get AI coaching
        </p>
      </div>
    )
  }

  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value)
      return <AiOutputDisplay value={parsed} />
    } catch {
      return <p className="text-sm text-foreground whitespace-pre-wrap leading-relaxed">{value}</p>
    }
  }

  if (typeof value === 'object' && !Array.isArray(value)) {
    const obj = value as Record<string, unknown>
    const { coach_note, ...rest } = obj
    return (
      <div className="space-y-5">
        {Object.entries(rest).map(([key, val]) => (
          <div key={key}>
            <h4 className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground mb-1">
              {formatKey(key)}
            </h4>
            <FieldValue value={val} />
          </div>
        ))}
        {coach_note !== undefined && (
          <div className="pt-4 border-t border-border">
            <h4 className="text-[10px] font-bold uppercase tracking-widest text-amber-500 mb-1.5">
              Coach Note
            </h4>
            <p className="text-sm text-amber-600 dark:text-amber-400 leading-relaxed italic">
              {String(coach_note)}
            </p>
          </div>
        )}
      </div>
    )
  }

  return (
    <pre className="text-xs text-foreground whitespace-pre-wrap">
      {JSON.stringify(value, null, 2)}
    </pre>
  )
}

// ─── Status badge ─────────────────────────────────────────────────────────────
const STATUS_STYLES: Record<string, string> = {
  approved: 'bg-emerald-500/15 text-emerald-500 border border-emerald-500/30',
  generated: 'bg-amber-500/15 text-amber-500 border border-amber-500/30',
  pending: 'bg-muted text-muted-foreground border border-border',
}

// ─── Main component ───────────────────────────────────────────────────────────
export function WorkspaceContent({
  project,
  layer,
  layerIndex,
  totalLayers,
  onNextLayer,
  allLayers,
}: {
  project: Project
  layer: Layer
  layerIndex: number
  totalLayers: number
  onNextLayer: () => void
  allLayers: Layer[]
}) {
  const router = useRouter()
  const isAuto = isAutoGeneratedLayer(layer.layer_key)
  const [userInput, setUserInput] = useState(extractUserInput(layer.user_input))
  const [aiOutput, setAiOutput] = useState<unknown>(layer.ai_output ?? null)
  const [autoGenerating, setAutoGenerating] = useState(false)
  const [autoError, setAutoError] = useState<string | null>(null)

  // ── Auto-generate logic ──────────────────────────────────────────────────
  // Fires when:
  //   1. This is an auto-generated layer (4–8)
  //   2. It has no output yet (pending)
  //   3. The previous layer (layer 3, manual_workflow) is approved
  const prevLayer = allLayers[layerIndex - 1] ?? null
  const shouldAutoGenerate =
    isAuto &&
    !aiOutput &&
    layer.status === 'pending' &&
    // For layer 4 (index 3): prev is layer 3 which must be approved
    // For layers 5–8: we auto-generate sequentially after layer 3 approval
    (layerIndex === 3
      ? prevLayer?.status === 'approved'
      : // For layers 5–8, check layer 3 (index 2) is approved
        (allLayers[2]?.status === 'approved'))

  const runAutoGenerate = useCallback(async () => {
    setAutoGenerating(true)
    setAutoError(null)
    try {
      // Use the approved layer 3 (manual_workflow) input as context seed for auto layers
      const layer3Input = extractUserInput(allLayers[2]?.user_input)

      const response = await callGenerateWebhook({
        projectId: project.id,
        layerKey: layer.layer_key,
        builderInput: layer3Input || 'Auto-generate based on previous approved layers.',
        mode: 'generate',
      })

      const generated = response.aiOutput ?? response
      setAiOutput(generated)
      await updateLayerStatus(layer.id, 'generated', null, generated)
      router.refresh()
    } catch (err) {
      setAutoError(err instanceof Error ? err.message : 'Auto-generation failed')
    } finally {
      setAutoGenerating(false)
    }
  }, [project.id, layer.layer_key, layer.id, allLayers, router])

  useEffect(() => {
    if (shouldAutoGenerate) {
      runAutoGenerate()
    }
  }, [shouldAutoGenerate, runAutoGenerate])

  return (
    <div className="flex-1 overflow-y-auto">
      {/* Sticky top bar */}
      <div className="sticky top-0 z-10 border-b border-border bg-background/95 backdrop-blur px-8 py-3 flex items-center gap-3">
        <span className="text-xs text-muted-foreground tabular-nums">
          Layer {layerIndex + 1} of {totalLayers}
        </span>
        <span className="text-muted-foreground/30">·</span>
        <h1 className="text-sm font-semibold">{layer.title}</h1>
        <span
          className={`px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide rounded-full ${STATUS_STYLES[layer.status] ?? STATUS_STYLES.pending}`}
        >
          {layer.status}
        </span>
        {/* Auto-generated badge */}
        {isAuto && (
          <span className="ml-1 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide rounded-full bg-violet-500/15 text-violet-500 border border-violet-500/30 flex items-center gap-1">
            <Zap className="h-2.5 w-2.5" />
            Auto Generated
          </span>
        )}
      </div>

      <div className="px-8 py-6 max-w-5xl">
        {/* Objective */}
        <div className="mb-6 px-4 py-3 rounded-lg bg-muted/40 border border-border">
          <p className="text-sm text-muted-foreground leading-relaxed">
            {LayerDescriptions[layer.layer_key as keyof typeof LayerDescriptions] ??
              'Complete this layer of your coaching journey.'}
          </p>
        </div>

        {/* Auto-error banner */}
        {autoError && (
          <div className="mb-4 px-3 py-2 rounded-lg bg-destructive/10 border border-destructive/20 text-sm text-destructive">
            Auto-generation error: {autoError} —{' '}
            <button
              className="underline font-medium"
              onClick={runAutoGenerate}
            >
              Retry
            </button>
          </div>
        )}

        {/* 2-col grid */}
        <div className="grid gap-6 lg:grid-cols-2 mb-6">
          {/* Input panel — hidden for auto-generated layers */}
          {!isAuto && (
            <div className="rounded-xl border border-border bg-card overflow-hidden flex flex-col">
              <div className="flex items-center gap-2 px-4 py-3 border-b border-border bg-muted/20">
                <PenLine className="h-3.5 w-3.5 text-muted-foreground" />
                <span className="text-xs font-semibold text-muted-foreground uppercase tracking-widest">
                  Your Input
                </span>
              </div>
              <div className="p-4 flex flex-col gap-3 flex-1">
                <Label htmlFor="input" className="text-sm font-medium">
                  Your Response
                </Label>
                <Textarea
                  id="input"
                  placeholder="Describe your project, problem, or answer the layer's prompt in plain text…"
                  value={userInput}
                  onChange={(e) => setUserInput(e.target.value)}
                  className="flex-1 min-h-52 resize-none text-sm leading-relaxed"
                />
                <p className="text-xs text-muted-foreground text-right">{userInput.length} characters</p>
              </div>
            </div>
          )}

          {/* AI Output panel — full width for auto layers */}
          <div
            className={`rounded-xl border border-border bg-card overflow-hidden flex flex-col ${isAuto ? 'lg:col-span-2' : ''}`}
          >
            <div className="flex items-center gap-2 px-4 py-3 border-b border-border bg-muted/20">
              <Sparkles className="h-3.5 w-3.5 text-muted-foreground" />
              <span className="text-xs font-semibold text-muted-foreground uppercase tracking-widest">
                AI Output
              </span>
              {isAuto && (
                <span className="ml-auto text-[10px] text-violet-500 font-medium flex items-center gap-1">
                  <Zap className="h-3 w-3" /> Automatically generated from your previous inputs
                </span>
              )}
            </div>
            <div className="p-4 overflow-auto max-h-[520px] flex-1">
              <AiOutputDisplay value={aiOutput} isLoading={autoGenerating} />
            </div>
          </div>
        </div>

        {/* Action bar */}
        <div className="rounded-xl border border-border bg-card px-4 py-4">
          <LayerActions
            project={project}
            layer={layer}
            userInput={userInput}
            aiOutput={aiOutput}
            onAiOutputChange={setAiOutput}
            layerIndex={layerIndex}
            totalLayers={totalLayers}
            onNextLayer={onNextLayer}
            isAutoLayer={isAuto}
          />
        </div>
      </div>
    </div>
  )
}